name: regex_transformer
description: >-
  Transforms text by taking capture groups matched by a [RegExp] and
  outputting them as plain text and/or evaluating them as expressions,
  as defined by an output template.
version: 0.1.0+2
homepage: https://github.com/james-alex/regex_transformer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  expressions: ^0.2.1

dev_dependencies:
  test: ^1.16.8
  pedantic: ^1.11.0
